/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as introspection from "./introspection";
export type { introspection };
import type * as structs from "./structs";
export type { structs };
