/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governanceStandard from "./governance_standard";
export { Box__factory } from "./Box__factory";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
